### ISSUE TITLE
[Crash] Version 1.1.2 crashes with DragonAPI

### ISSUE THREAD

**Issue by FalsePattern** [GTNewHorizons/lwjgl3ify#1]
Mod list:
- GTNHMixins 2.1.11
- lwjgl3ify 1.1.2
- ChromatiCraft V31b
- DragonAPI V31b

It seems like lwjgl3ify breaks Reika's glsl shader loading code.

[fml-client-latest.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10490322/fml-client-latest.log)

**Comment by eigenraven** [comment]
Looks like Reika is using the wrong opengl api to get shader linking status:
<https://github.com/ReikaKalseki/DragonAPI/blob/master/IO/Shaders/ShaderProgram.java#L391-L395> - here the get calls must be `glGetProgrami` not `glGetShaderi`, because they operate on the linked program and not individual shaders. See <https://docs.gl/gl2/glLinkProgram> for reference. Because it seems Reika is still updating mods, it'd be better to get it fixed upstream than me working around the issue.

**Comment by eigenraven** [comment]
Fixed in recent DragonAPI source updates, the next build should work when that gets released
